import react from "@vitejs/plugin-react-swc";
import path, { resolve } from "path";
import { defineConfig } from "vite";
import dts from "vite-plugin-dts";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), dts({ rollupTypes: true })],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  build: {
    emptyOutDir: true,
    lib: {
      entry: {
        core: resolve(__dirname, "src/core/main/index.ts"),
        render: resolve(__dirname, "src/render/index.ts"),
        ui: resolve(__dirname, "src/ui/index.ts"),
        "web-blocks": resolve(__dirname, "src/web-blocks/index.ts"),
        tailwind: resolve(__dirname, "src/tailwind/index.ts"),
        runtime: resolve(__dirname, "src/runtime.ts"),
      },
      formats: ["es", "cjs"],
    },
    rollupOptions: {
      treeshake: true,
      output: {
        globals: {
          "react-dom": "ReactDom",
          react: "React",
          "react/jsx-runtime": "ReactJsxRuntime",
        },
      },

      // make sure to externalize deps that shouldn't be bundled
      // into your library
      external: [
        "react/jsx-runtime",
        "react/jsx-dev-runtime",
        "@chaibuilder/runtime",
        "@floating-ui/dom",
        "@floating-ui/react-dom",
        "react-error-boundary",
        "@mhsdesign/jit-browser-tailwindcss",
        "@radix-ui/react-accordion",
        "@radix-ui/react-alert-dialog",
        "@radix-ui/react-avatar",
        "@radix-ui/react-checkbox",
        "@radix-ui/react-context-menu",
        "@radix-ui/react-dialog",
        "@radix-ui/react-dropdown-menu",
        "@radix-ui/react-hover-card",
        "@radix-ui/react-icons",
        "@radix-ui/react-label",
        "@radix-ui/react-menubar",
        "@radix-ui/react-navigation-menu",
        "@radix-ui/react-popover",
        "@radix-ui/react-scroll-area",
        "@radix-ui/react-select",
        "@radix-ui/react-separator",
        "@radix-ui/react-slot",
        "@radix-ui/react-slider",
        "@radix-ui/react-switch",
        "@radix-ui/react-tabs",
        "@radix-ui/react-toast",
        "@radix-ui/react-toggle",
        "@radix-ui/react-tooltip",
        "@react-hookz/web",
        "react-arborist",
        "jotai/utils",
        "sonner",
        "@rjsf/core",
        "react-hook-form",
        "@hookform/resolvers",
        "@rjsf/utils",
        "@rjsf/validator-ajv8",
        "@tailwindcss/aspect-ratio",
        "@tailwindcss/forms",
        "@tailwindcss/line-clamp",
        "@tailwindcss/typography",
        "@tailwindcss/container-queries",
        "class-variance-authority",
        "@bobthered/tailwindcssPaletteGenerator",
        "clsx",
        "cmdk",
        "framer-motion",
        "date-fns",
        "flagged",
        "fuse.js",
        "himalaya",
        "tree-model",
        "i18next",
        "jotai",
        "prop-types",
        "lodash",
        "lodash-es",
        "culori",
        "lucide-react",
        "react",
        "react-autosuggest",
        "react-colorful",
        "react-dom",
        "react-frame-component",
        "react-hotkeys-hook",
        "react-i18next",
        "react-json-view",
        "@tiptap/react",
        "@tiptap/pm",
        "@tiptap/extension-link",
        "@tiptap/starter-kit",
        "@tiptap/extension-underline",
        "@tiptap/extension-text-align",
        "@tiptap/extension-bullet-list",
        "@tiptap/extension-ordered-list",
        "@tiptap/extension-placeholder",
        "@tiptap/extension-text-align",
        "@tiptap/extension-text-style",
        "@tiptap/extension-highlight",
        "react-wrap-balancer",
        "tailwind-merge",
        "tailwindcss-animate",
        "undo-manager",
        "zod",
      ],
    },
  },
});
