import { ChaiBlock } from "@/types/common";

export const BLOCKS: ChaiBlock<any>[] = [
  {
    content: "Hello World",
    styles2: "#styles:,bg-red-500",
    _type: "CustomBlock",
    _id: "kpDBqj",
    _parent: "",
  },
  {
    styles: "#styles:,grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-3",
    repeaterItems: "{{#blogs}}",
    tag: "ul",
    limit: "3",
    filter: "most-viewed",
    sort: "",
    _type: "Repeater",
    _id: "CockAq",
    _parent: "",
  },
  {
    styles: "#styles:,",
    _type: "RepeaterItem",
    _id: "ireCuv",
    _name: "Repeater Item",
    _parent: "CockAq",
  },
  {
    styles:
      "#styles:,flex flex-col bg-white border border-gray-200 shadow-2xs rounded-xl dark:bg-neutral-900 dark:border-neutral-700 dark:shadow-neutral-700/70",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "akBxzu",
    _name: "Box",
    _parent: "ireCuv",
  },
  {
    styles: "#styles:,w-full h-auto rounded-t-xl",
    image: "{{$index.image}} ",
    alt: "Card Image",
    lazyLoading: "true",
    width: "",
    height: "",
    mobileImage: "",
    assetId: "",
    _type: "Image",
    _id: "fAAuvh",
    _parent: "akBxzu",
  },
  {
    styles: "#styles:,p-4 md:p-5",
    backgroundImage: "",
    tag: "div",
    _type: "Box",
    _id: "Dpfwab",
    _name: "Box",
    _parent: "akBxzu",
  },
  {
    tag: "h3",
    styles: "#styles:,text-lg font-bold",
    content: "{{$index.title}}",
    _type: "Heading",
    _id: "uaxjam",
    _parent: "Dpfwab",
  },
  {
    styles: "#styles:,mt-1",
    content: "{{$index.content}}",
    _type: "Paragraph",
    _id: "colsAo",
    _parent: "Dpfwab",
  },
  {
    styles:
      "#styles:,mt-2 py-2 px-3 inline-flex justify-center items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 focus:outline-hidden focus:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none",
    content: " Go to blog post ",
    link: { href: "/{{$index.slug}}", type: "url", target: "_self" },
    _type: "Link",
    _id: "fqqdpl",
    _parent: "Dpfwab",
  },
  { _type: "@chai/ai-context", _value: "" },
];
