export const D_Blocks = [
  {
    _id: "lrikCA",
    tag: "div",
    _type: "Box",
    styles: "#styles:,grid grid-cols-2",
    backgroundImage: "",
  },
  {
    _id: "agbitd",
    tag: "div",
    _type: "Box",
    styles: "#styles:,",
    _parent: "lrikCA",
    backgroundImage: "",
  },
  {
    _id: "ztsooz",
    _type: "Form",
    action: "/api/form/submit",
    styles: "#styles:,max-w-sm mx-auto",
    errorMessage: "Something went wrong. Please try again",
    successMessage: "Thank you for your submission.",
    _parent: "agbitd",
  },
  {
    _id: "hbdfdn",
    tag: "h2",
    _type: "Heading",
    styles: "#styles:,text-3xl md:my-[15px]",
    _parent: "ztsooz",
    content: "Titre principal ici",
  },
  {
    _id: "whDfyi",
    tag: "div",
    _name: "Box",
    _type: "Box",
    styles: "#styles:,mb-5",
    _parent: "ztsooz",
    backgroundImage: "",
  },
  {
    _id: "egabjj",
    _type: "Label",
    styles: "#styles:,block mb-2 text-sm font-medium text-gray-900 dark:text-white",
    _parent: "whDfyi",
    content: "Your email",
    styles_attrs: { for: "email" },
  },
  {
    _id: "irifjz",
    _type: "Input",
    label: "Label",
    styles:
      "#styles:,shadow-xs bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-xs-light",
    _parent: "whDfyi",
    required: "",
    fieldName: "fieldName",
    inputType: "email",
    showLabel: false,
    inputStyles: "#styles:,w-full p-1",
    placeholder: "name@flowbite.com",
    styles_attrs: { id: "email" },
  },
  {
    _id: "kedzmB",
    tag: "div",
    _name: "Box",
    _type: "Box",
    styles: "#styles:,mb-5",
    _parent: "ztsooz",
    backgroundImage: "",
  },
  {
    _id: "srldgq",
    _type: "Label",
    styles: "#styles:,block mb-2 text-sm font-medium text-gray-900 dark:text-white",
    _parent: "kedzmB",
    content: "Your password",
    styles_attrs: { for: "password" },
  },
  {
    _id: "eDmzex",
    _type: "Input",
    label: "Label",
    styles:
      "#styles:,shadow-xs bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-xs-light",
    _parent: "kedzmB",
    required: "",
    fieldName: "fieldName",
    inputType: "password",
    showLabel: false,
    inputStyles: "#styles:,w-full p-1",
    placeholder: "Placeholder",
    styles_attrs: { id: "password" },
  },
  {
    _id: "atbdlx",
    tag: "div",
    _name: "Box",
    _type: "Box",
    styles: "#styles:,mb-5",
    _parent: "ztsooz",
    backgroundImage: "",
  },
  {
    _id: "CjDwbg",
    _type: "Label",
    styles: "#styles:,block mb-2 text-sm font-medium text-gray-900 dark:text-white",
    _parent: "atbdlx",
    content: "Repeat password",
    styles_attrs: { for: "repeat-password" },
  },
  {
    _id: "Dumejd",
    _type: "Input",
    label: "Label",
    styles:
      "#styles:,shadow-xs bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-xs-light",
    _parent: "atbdlx",
    required: "",
    fieldName: "fieldName",
    inputType: "password",
    showLabel: false,
    inputStyles: "#styles:,w-full p-1",
    placeholder: "Placeholder",
    styles_attrs: { id: "repeat-password" },
  },
  {
    _id: "hiixcm",
    tag: "div",
    _name: "Box",
    _type: "Box",
    styles: "#styles:,flex items-start mb-5",
    _parent: "ztsooz",
    backgroundImage: "",
  },
  {
    _id: "AxyfnD",
    tag: "div",
    _name: "Box",
    _type: "Box",
    styles: "#styles:,flex items-center h-5",
    _parent: "hiixcm",
    backgroundImage: "",
  },
  {
    _id: "dwDjcq",
    _type: "Checkbox",
    label: "Label",
    styles:
      "#styles:,w-4 h-4 border border-gray-300 rounded-sm bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800",
    _parent: "AxyfnD",
    checked: false,
    required: "",
    fieldName: "fieldName",
    inputType: "checkbox",
    showLabel: false,
    inputStyles: "#styles:,",
    styles_attrs: { id: "terms", value: "" },
  },
  {
    _id: "yAfndy",
    _type: "Label",
    styles: "#styles:,ms-2 text-sm font-medium text-gray-900 dark:text-gray-300",
    _parent: "hiixcm",
    content: "",
    styles_attrs: { for: "terms" },
  },
  {
    _id: "sBzbAb",
    _type: "Text",
    styles: "#styles:,text-black",
    _parent: "yAfndy",
    content: "I agree with the ",
  },
  {
    _id: "cykcBy",
    link: { href: "#" },
    _type: "Link",
    styles: "#styles:,text-blue-600 hover:underline dark:text-blue-500",
    _parent: "yAfndy",
    content: "terms and conditions",
  },
  {
    _id: "BriBhz",
    icon: "",
    link: { href: "", type: "url", target: "_self" },
    _type: "Button",
    styles:
      "#styles:,text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800",
    _parent: "ztsooz",
    content: "Register new account",
    iconPos: "order-last",
    iconSize: 16,
    styles_attrs: { type: "submit" },
  },
  { _type: "@chai/ai-context", _value: "" },
  {
    _id: "peslfp",
    tag: "div",
    _type: "Box",
    styles: "#styles:,",
    _parent: "lrikCA",
    backgroundImage: "",
  },
  {
    _id: "ztsooz",
    _type: "Form",
    action: "/api/form/submit",
    styles: "#styles:,max-w-sm mx-auto",
    errorMessage: "Something went wrong. Please try again",
    successMessage: "Thank you for your submission.",
    _parent: "peslfp",
  },
  {
    _id: "hbdfdn",
    tag: "h2",
    _type: "Heading",
    styles: "#styles:,text-3xl md:my-[15px]",
    _parent: "ztsooz",
    content: "Titre principal ici",
  },
  {
    _id: "whDfyi",
    tag: "div",
    _name: "Box",
    _type: "Box",
    styles: "#styles:,mb-5",
    _parent: "ztsooz",
    backgroundImage: "",
  },
  {
    _id: "egabjj",
    _type: "Label",
    styles: "#styles:,block mb-2 text-sm font-medium text-gray-900 dark:text-white",
    _parent: "whDfyi",
    content: "Your email",
    styles_attrs: { for: "email" },
  },
  {
    _id: "irifjz",
    _type: "Input",
    label: "Label",
    styles:
      "#styles:,shadow-xs bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-xs-light",
    _parent: "whDfyi",
    required: "",
    fieldName: "fieldName",
    inputType: "email",
    showLabel: false,
    inputStyles: "#styles:,w-full p-1",
    placeholder: "name@flowbite.com",
    styles_attrs: { id: "email" },
  },
  {
    _id: "kedzmB",
    tag: "div",
    _name: "Box",
    _type: "Box",
    styles: "#styles:,mb-5",
    _parent: "ztsooz",
    backgroundImage: "",
  },
  {
    _id: "srldgq",
    _type: "Label",
    styles: "#styles:,block mb-2 text-sm font-medium text-gray-900 dark:text-white",
    _parent: "kedzmB",
    content: "Your password",
    styles_attrs: { for: "password" },
  },
  {
    _id: "eDmzex",
    _type: "Input",
    label: "Label",
    styles:
      "#styles:,shadow-xs bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-xs-light",
    _parent: "kedzmB",
    required: "",
    fieldName: "fieldName",
    inputType: "password",
    showLabel: false,
    inputStyles: "#styles:,w-full p-1",
    placeholder: "Placeholder",
    styles_attrs: { id: "password" },
  },
  {
    _id: "atbdlx",
    tag: "div",
    _name: "Box",
    _type: "Box",
    styles: "#styles:,mb-5",
    _parent: "ztsooz",
    backgroundImage: "",
  },
  {
    _id: "CjDwbg",
    _type: "Label",
    styles: "#styles:,block mb-2 text-sm font-medium text-gray-900 dark:text-white",
    _parent: "atbdlx",
    content: "Repeat password",
    styles_attrs: { for: "repeat-password" },
  },
  {
    _id: "Dumejd",
    _type: "Input",
    label: "Label",
    styles:
      "#styles:,shadow-xs bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-xs-light",
    _parent: "atbdlx",
    required: "",
    fieldName: "fieldName",
    inputType: "password",
    showLabel: false,
    inputStyles: "#styles:,w-full p-1",
    placeholder: "Placeholder",
    styles_attrs: { id: "repeat-password" },
  },
  {
    _id: "hiixcm",
    tag: "div",
    _name: "Box",
    _type: "Box",
    styles: "#styles:,flex items-start mb-5",
    _parent: "ztsooz",
    backgroundImage: "",
  },
  {
    _id: "AxyfnD",
    tag: "div",
    _name: "Box",
    _type: "Box",
    styles: "#styles:,flex items-center h-5",
    _parent: "hiixcm",
    backgroundImage: "",
  },
  {
    _id: "dwDjcq",
    _type: "Checkbox",
    label: "Label",
    styles:
      "#styles:,w-4 h-4 border border-gray-300 rounded-sm bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800",
    _parent: "AxyfnD",
    checked: false,
    required: "",
    fieldName: "fieldName",
    inputType: "checkbox",
    showLabel: false,
    inputStyles: "#styles:,",
    styles_attrs: { id: "terms", value: "" },
  },
  {
    _id: "yAfndy",
    _type: "Label",
    styles: "#styles:,ms-2 text-sm font-medium text-gray-900 dark:text-gray-300",
    _parent: "hiixcm",
    content: "",
    styles_attrs: { for: "terms" },
  },
  {
    _id: "sBzbAb",
    _type: "Text",
    styles: "#styles:,text-black",
    _parent: "yAfndy",
    content: "I agree with the ",
  },
  {
    _id: "cykcBy",
    link: { href: "#" },
    _type: "Link",
    styles: "#styles:,text-blue-600 hover:underline dark:text-blue-500",
    _parent: "yAfndy",
    content: "terms and conditions",
  },
  {
    _id: "BriBhz",
    icon: "",
    link: { href: "", type: "url", target: "_self" },
    _type: "Button",
    styles:
      "#styles:,text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800",
    _parent: "ztsooz",
    content: "Register new account",
    iconPos: "order-last",
    iconSize: 16,
    styles_attrs: { type: "submit" },
  },
  { _type: "@chai/ai-context", _value: "" },
  { _type: "@chai/ai-context", _value: "" },
];
