import { noop } from "lodash-es";
// import "./body";
// import "./box";
// import "./heading";
// import "./paragraph";
// import "./span";
// import "./rte";
// import "./button";
// import "./link";
// import "./list";
// import "./icon";
// import "./image";
// import "./slot";
// import "./video";
// import "./custom-html";
// import "./divider";
// import "./line-break";
// import "./text";
// import "./table";
// import "./form/form.tsx";
// import "./form/input.tsx";
// import "./form/textarea.tsx";
// import "./form/select.tsx";
// import "./form/checkbox.tsx";
// import "./form/radio.tsx";
// import "./form/form-button.tsx";

const loadWebBlocks = noop;

export { loadWebBlocks };
