-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
--> statement-breakpoint
CREATE TABLE "library_templates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"user" text,
	"name" text,
	"description" text,
	"pageId" uuid,
	"pageType" text,
	"library" uuid,
	"preview" text
);
--> statement-breakpoint
ALTER TABLE "library_templates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "webhook_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "webhook_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"provider" text,
	"eventType" text,
	"payload" jsonb,
	"userId" uuid,
	"clientId" uuid
);
--> statement-breakpoint
ALTER TABLE "webhook_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"user" uuid,
	"app" uuid,
	"role" varchar DEFAULT 'editor',
	"permissions" jsonb,
	"status" text DEFAULT 'active' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app_users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app_domains" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"app" uuid,
	"hosting" text DEFAULT 'vercel',
	"hostingProjectId" text DEFAULT 'env',
	"subdomain" text,
	"domain" text,
	"domainConfigured" boolean DEFAULT false
);
--> statement-breakpoint
ALTER TABLE "app_domains" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint

--> statement-breakpoint
CREATE TABLE "app_pages_revisions" (
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"slug" text NOT NULL,
	"lang" text DEFAULT '' NOT NULL,
	"seo" jsonb DEFAULT '{}'::jsonb,
	"app" uuid NOT NULL,
	"buildTime" boolean DEFAULT false,
	"id" uuid NOT NULL,
	"name" text NOT NULL,
	"primaryPage" uuid,
	"blocks" jsonb DEFAULT '[]'::jsonb,
	"currentEditor" text,
	"changes" jsonb,
	"collection" text DEFAULT 'page',
	"partialBlocks" text,
	"links" text,
	"online" boolean DEFAULT true,
	"pageType" text,
	"parent" uuid,
	"lastSaved" timestamp with time zone,
	"dynamic" boolean DEFAULT false,
	"uid" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"type" varchar DEFAULT 'published',
	"libRefId" uuid,
	"dynamicSlugCustom" varchar DEFAULT '',
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"tracking" jsonb DEFAULT '{}'::jsonb,
	"jsonld" jsonb DEFAULT '{}'::jsonb,
	"globalJsonLds" jsonb DEFAULT '[]'::jsonb,
	"designTokens" jsonb
);
--> statement-breakpoint
ALTER TABLE "app_pages_revisions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "apps_online" (
	"id" uuid PRIMARY KEY NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"name" varchar,
	"user" uuid,
	"settings" jsonb DEFAULT '{}'::jsonb,
	"theme" jsonb DEFAULT '{}'::jsonb,
	"fallbackLang" text DEFAULT 'en',
	"languages" jsonb DEFAULT '[]'::jsonb,
	"changes" jsonb,
	"configData" jsonb,
	"apiKey" text,
	"deletedAt" timestamp with time zone,
	"client" uuid,
	"designTokens" jsonb DEFAULT '{}'::jsonb
);
--> statement-breakpoint
ALTER TABLE "apps_online" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "clients" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text,
	"status" text DEFAULT 'active',
	"billingStartDate" date,
	"startDate" date,
	"settings" jsonb DEFAULT '{}'::jsonb,
	"loginHtml" text,
	"features" jsonb DEFAULT '{}'::jsonb,
	"paymentConfig" jsonb DEFAULT '{}'::jsonb,
	"theme" text,
	"helpHtml" text,
	"madeWithBadge" text
);
--> statement-breakpoint
ALTER TABLE "clients" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "ai_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"model" text,
	"totalDuration" numeric,
	"error" text,
	"totalTokens" numeric,
	"tokenUsage" jsonb,
	"user" uuid,
	"client" varchar,
	"cost" double precision DEFAULT '0',
	"prompt" text
);
--> statement-breakpoint
ALTER TABLE "ai_logs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app_api_keys" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"apiKey" text DEFAULT '',
	"app" uuid,
	"status" text DEFAULT 'ACTIVE'
);
--> statement-breakpoint
ALTER TABLE "app_api_keys" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "libraries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"name" varchar,
	"app" uuid,
	"type" varchar,
	"status" text DEFAULT 'active' NOT NULL,
	"client" uuid
);
--> statement-breakpoint
ALTER TABLE "libraries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "apps" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"name" varchar,
	"user" uuid,
	"settings" jsonb DEFAULT '{}'::jsonb,
	"theme" jsonb DEFAULT '{}'::jsonb,
	"fallbackLang" text DEFAULT 'en',
	"languages" jsonb DEFAULT '[]'::jsonb,
	"changes" jsonb,
	"configData" jsonb,
	"deletedAt" timestamp with time zone,
	"client" uuid,
	"designTokens" jsonb DEFAULT '{}'::jsonb
);
--> statement-breakpoint
ALTER TABLE "apps" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "library_items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"library" uuid,
	"name" text,
	"description" text,
	"blocks" jsonb DEFAULT '[]'::jsonb,
	"preview" text,
	"group" text DEFAULT 'general',
	"user" text,
	"html" text
);
--> statement-breakpoint
ALTER TABLE "library_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app_assets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"app" uuid,
	"name" text,
	"description" text,
	"url" text,
	"size" text,
	"folderId" text,
	"thumbnailUrl" text,
	"duration" numeric,
	"format" text,
	"width" numeric,
	"height" numeric,
	"createdBy" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"type" text,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "app_assets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app_form_submissions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"app" uuid,
	"formData" json,
	"additionalData" json,
	"formName" text DEFAULT '',
	"pageUrl" text
);
--> statement-breakpoint
ALTER TABLE "app_form_submissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app_pages_online" (
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"slug" text NOT NULL,
	"lang" text DEFAULT '' NOT NULL,
	"seo" jsonb DEFAULT '{}'::jsonb,
	"app" uuid NOT NULL,
	"buildTime" boolean DEFAULT false,
	"id" uuid PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"primaryPage" uuid,
	"blocks" jsonb DEFAULT '[]'::jsonb,
	"currentEditor" text,
	"changes" jsonb,
	"collection" text DEFAULT 'page',
	"partialBlocks" text,
	"links" text,
	"online" boolean DEFAULT true,
	"pageType" text,
	"parent" uuid,
	"lastSaved" timestamp with time zone,
	"dynamic" boolean DEFAULT false,
	"libRefId" uuid,
	"dynamicSlugCustom" varchar DEFAULT '',
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"tracking" jsonb DEFAULT '{}'::jsonb,
	"jsonld" jsonb DEFAULT '{}'::jsonb,
	"globalJsonLds" jsonb DEFAULT '[]'::jsonb,
	"designTokens" jsonb
);
--> statement-breakpoint
ALTER TABLE "app_pages_online" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app_user_plans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"user" uuid,
	"planId" text DEFAULT 'FREE',
	"nextBilledAt" timestamp NOT NULL,
	"subscriptionId" text,
	"client" uuid,
	"scheduledForCancellation" boolean DEFAULT false
);
--> statement-breakpoint
ALTER TABLE "app_user_plans" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app_pages" (
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"slug" text NOT NULL,
	"lang" text DEFAULT '' NOT NULL,
	"seo" jsonb DEFAULT '{}'::jsonb,
	"app" uuid NOT NULL,
	"buildTime" boolean DEFAULT false,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"primaryPage" uuid,
	"blocks" jsonb DEFAULT '[]'::jsonb,
	"currentEditor" text,
	"changes" jsonb,
	"collection" text DEFAULT 'page',
	"online" boolean DEFAULT false,
	"parent" uuid,
	"pageType" text,
	"lastSaved" timestamp with time zone,
	"dynamic" boolean DEFAULT false,
	"libRefId" uuid,
	"dynamicSlugCustom" varchar DEFAULT '',
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"tracking" jsonb DEFAULT '{}'::jsonb,
	"jsonld" jsonb DEFAULT '{}'::jsonb,
	"globalJsonLds" jsonb DEFAULT '[]'::jsonb,
	"links" text,
	"partialBlocks" text,
	"designTokens" jsonb
);
--> statement-breakpoint
ALTER TABLE "app_pages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app_pages_metadata" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "app_pages_metadata_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"slug" varchar NOT NULL,
	"pageId" uuid DEFAULT gen_random_uuid(),
	"publishedAt" timestamp with time zone,
	"pageType" varchar,
	"pageBlocks" varchar,
	"dataBindings" varchar,
	"pageContent" varchar,
	"dataProviders" varchar,
	"app" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "app_pages_metadata_pkey" PRIMARY KEY("slug","app")
);
--> statement-breakpoint
ALTER TABLE "app_pages_metadata" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "library_templates" ADD CONSTRAINT "library_templates_library_fkey" FOREIGN KEY ("library") REFERENCES "public"."libraries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_events" ADD CONSTRAINT "webhook_events_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_events" ADD CONSTRAINT "webhook_events_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_users" ADD CONSTRAINT "app_users_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_users" ADD CONSTRAINT "app_users_user_fkey" FOREIGN KEY ("user") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_domains" ADD CONSTRAINT "app_domains_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_pages_revisions" ADD CONSTRAINT "app_pages_revisions_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "apps_online" ADD CONSTRAINT "apps_online_client_fkey" FOREIGN KEY ("client") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "apps_online" ADD CONSTRAINT "apps_online_user_fkey" FOREIGN KEY ("user") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_logs" ADD CONSTRAINT "ai_logs_user_fkey" FOREIGN KEY ("user") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_api_keys" ADD CONSTRAINT "app_api_keys_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "libraries" ADD CONSTRAINT "libraries_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "libraries" ADD CONSTRAINT "libraries_client_fkey" FOREIGN KEY ("client") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "apps" ADD CONSTRAINT "apps_client_fkey" FOREIGN KEY ("client") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "apps" ADD CONSTRAINT "apps_user_fkey" FOREIGN KEY ("user") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "library_items" ADD CONSTRAINT "library_items_library_fkey" FOREIGN KEY ("library") REFERENCES "public"."libraries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_assets" ADD CONSTRAINT "app_assets_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_form_submissions" ADD CONSTRAINT "app_form_submissions_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_pages_online" ADD CONSTRAINT "app_pages_online_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_plans" ADD CONSTRAINT "app_user_plans_client_fkey" FOREIGN KEY ("client") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_user_plans" ADD CONSTRAINT "app_user_plans_user_fkey" FOREIGN KEY ("user") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_pages" ADD CONSTRAINT "app_pages_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_pages" ADD CONSTRAINT "app_pages_parent_fkey" FOREIGN KEY ("parent") REFERENCES "public"."app_pages"("id") ON DELETE no action ON UPDATE no action;
