name: Generate Sitemap

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Sitemap
        uses: tenelabs/docsify-sitemap-action@v1
        with:
          baseUrl: https://docs.chaibuilder.com
          docsPath: ./docs
          sitemapPath: ./docs/sitemap.xml

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/sitemap.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update sitemap" && git push)
